CREATE TABLE `esocial` (
`filial` VARCHAR( 4 ) NOT NULL ,
`cpfTrab` VARCHAR( 11 ) NOT NULL ,
`nisTrab` VARCHAR( 11 ) NOT NULL ,
`nmTrab` VARCHAR( 70 ) NOT NULL ,
`sexo` VARCHAR( 1 ) NOT NULL ,
`racaCor` VARCHAR( 1 ) NOT NULL ,
`estCiv` VARCHAR( 1 ) NOT NULL ,
`grauInstr` VARCHAR( 2 ) NOT NULL ,
`nmSoc` VARCHAR( 70 ) NOT NULL ,
`dtNascto1` VARCHAR( 8 ) NOT NULL,
`codMunic1` VARCHAR( 7 ) NOT NULL ,
`uf1` VARCHAR( 2 ) NOT NULL ,
`paisNascto` VARCHAR ( 3 ) NOT NULL ,
`paisNac` VARCHAR( 3 ) NOT NULL ,
`nmMae` VARCHAR( 70 ) NOT NULL ,
`nmPai` VARCHAR( 70 ) NOT NULL ,
`nrCtps` VARCHAR( 11 ) NOT NULL ,
`serieCtps` VARCHAR( 5 ) NOT NULL ,
`ufCtps` VARCHAR( 2 ) NOT NULL ,
`nrRic` VARCHAR( 14 ) NOT NULL ,
`orgaoEmissor1` VARCHAR( 20 ) NOT NULL ,
`dtExped1` VARCHAR( 8 ) NOT NULL ,
`nrRg` VARCHAR( 14 ) NOT NULL ,
`orgaoEmissor2` VARCHAR( 20 ) NOT NULL ,
`dtExped2` VARCHAR( 8 ) NOT NULL ,
`nrRne` VARCHAR( 14 ) NOT NULL ,
`orgaoEmissor3` VARCHAR( 20 ) NOT NULL ,
`dtExped3` VARCHAR( 8 ) NOT NULL ,
`nrOc` VARCHAR( 14 ) NOT NULL ,
`orgaoEmissor4` VARCHAR( 20 ) NOT NULL ,
`dtExped4` VARCHAR( 8 ) NOT NULL ,
`dtValid1` VARCHAR( 8 ) NOT NULL ,
`nrRegCnh` VARCHAR( 12 ) NOT NULL ,
`dtExped` VARCHAR( 8 ) NOT NULL , 
`ufCnh` VARCHAR( 2 ) NOT NULL ,
`dtValid` VARCHAR( 8 ) NOT NULL ,
`dtPriHab` VARCHAR( 8 ) NOT NULL ,
`categoriaCnh` VARCHAR( 2 ) NOT NULL , 
`tpLograd` VARCHAR( 4 ) NOT NULL ,  
`rua` VARCHAR( 80 ) NOT NULL ,
`nrLograd` VARCHAR( 10 ) NOT NULL ,
`complemento` VARCHAR( 30 ) NOT NULL ,
`bairro` VARCHAR( 60 ) NOT NULL ,
`cep` VARCHAR( 8 ) NOT NULL ,
`ibge` VARCHAR( 7 ) NOT NULL ,
`uf` VARCHAR( 2 ) NOT NULL , 
`cidade` VARCHAR( 40 ) NOT NULL , 
`paisResid` VARCHAR( 3 ) NOT NULL ,
`dscLograd1` VARCHAR( 80 ) NOT NULL ,
`nrLograd1` VARCHAR( 10 ) NOT NULL ,
`complemento1` VARCHAR( 30 ) NOT NULL,
`bairro1` VARCHAR( 60 ) NOT NULL,
`nmCid` VARCHAR( 50 ) NOT NULL ,
`codPostal` VARCHAR( 12 ) NOT NULL , 
`dtChegada` VARCHAR( 8 ) NOT NULL ,
`classTrabEstrang` VARCHAR( 2 ) ,
`casadoBr` VARCHAR( 1 ) NOT NULL,
`filhosBr` VARCHAR( 1 ) NOT NULL ,
`defFisica` VARCHAR( 1 ) NOT NULL ,
`defVisual` VARCHAR( 1 ) NOT NULL ,
`defAuditiva` VARCHAR( 1 ) NOT NULL ,
`defMental` VARCHAR( 1 ) NOT NULL , 
`defIntelectual` VARCHAR( 1 ) NOT NULL , 
`reabReadap` VARCHAR( 1 ) NOT NULL ,
`observacao` VARCHAR( 255 ) NOT NULL ,
`tpDep` VARCHAR( 2 ) NOT NULL,
`nmDep` VARCHAR( 70 ) NOT NULL,
`dtNascto` VARCHAR( 8 ) NOT NULL ,
`cpfDep` VARCHAR( 11 ) NOT NULL ,
`depIRRF` VARCHAR( 1 ) NOT NULL ,
`depSF` VARCHAR( 1 ) NOT NULL ,
`incTrab` VARCHAR( 1 ) NOT NULL ,
`trabAposent` VARCHAR( 1 ) NOT NULL ,
`fonePrinc` VARCHAR( 13 ) NOT NULL , 
`foneAlternat` VARCHAR( 13 ) NOT NULL , 
`emailPrinc` VARCHAR( 60 ) NOT NULL ,
`emailAltern` VARCHAR( 60 ) NOT NULL ,
`id` INT NOT NULL AUTO_INCREMENT ,
UNIQUE (
`id` 
)
);
